version: 0.2

phases:
  install:
    commands:
        - sudo apt-get update
        - curl "https://bootstrap.pypa.io/pip/2.7/get-pip.py" -o "get-pip.py"
        - python get-pip.py
        - pip install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
